// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type Mutation struct {
}

type Query struct {
}

type User struct {
	UUID           uuid.UUID    `json:"uuid"`
	Email          string       `json:"email"`
	Username       string       `json:"username"`
	Password       string       `json:"password"`
	ProfileImg     *string      `json:"profileImg,omitempty"`
	ProfileMessage *string      `json:"profileMessage,omitempty"`
	Status         *string      `json:"status,omitempty"`
	Rank           *string      `json:"rank,omitempty"`
	FriendsList    []*uuid.UUID `json:"friendsList,omitempty"`
	FriendsRequest []*uuid.UUID `json:"friendsRequest,omitempty"`
	CreatedAt      *string      `json:"createdAt,omitempty"`
}
