package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"fmt"
	"time"

	"github.com/Evantopian/Nexus/graph/model"
	"github.com/Evantopian/Nexus/graph/resolver/chat"
	"github.com/google/uuid"
)

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, conversationID uuid.UUID, body string, replyToID *uuid.UUID) (*model.Message, error) {
	return chat.SendMessage(ctx, conversationID, body)
}

// StartConversation is the resolver for the startConversation field.
func (r *mutationResolver) StartConversation(ctx context.Context, participantIds []uuid.UUID) (*model.Conversation, error) {
	return chat.StartConversation(ctx, participantIds)
}

// CreateServer is the resolver for the createServer field.
func (r *mutationResolver) CreateServer(ctx context.Context, name string) (*model.Server, error) {
	return chat.CreateServer(ctx, name)
}

// JoinServer is the resolver for the joinServer field.
func (r *mutationResolver) JoinServer(ctx context.Context, serverID uuid.UUID) (bool, error) {
	return chat.JoinServer(ctx, serverID)
}

// LeaveServer is the resolver for the leaveServer field.
func (r *mutationResolver) LeaveServer(ctx context.Context, serverID uuid.UUID) (bool, error) {
	return chat.LeaveServer(ctx, serverID)
}

// DeleteServer is the resolver for the deleteServer field.
func (r *mutationResolver) DeleteServer(ctx context.Context, serverID uuid.UUID) (bool, error) {
	return chat.DeleteServer(ctx, serverID)
}

// CreateChannel is the resolver for the createChannel field.
func (r *mutationResolver) CreateChannel(ctx context.Context, serverID uuid.UUID, name string, typeArg model.ChannelType, categoryID *uuid.UUID) (*model.Channel, error) {
	return chat.CreateChannel(ctx, serverID, name, typeArg, categoryID)
}

// DeleteChannel is the resolver for the deleteChannel field.
func (r *mutationResolver) DeleteChannel(ctx context.Context, channelID uuid.UUID) (bool, error) {
	return chat.DeleteChannel(ctx, channelID)
}

// LeaveChannel is the resolver for the leaveChannel field.
func (r *mutationResolver) LeaveChannel(ctx context.Context, channelID uuid.UUID) (bool, error) {
	return chat.LeaveChannel(ctx, channelID)
}

// PinMessage is the resolver for the pinMessage field.
func (r *mutationResolver) PinMessage(ctx context.Context, messageID uuid.UUID) (bool, error) {
	return chat.PinMessage(ctx, messageID)
}

// UnpinMessage is the resolver for the unpinMessage field.
func (r *mutationResolver) UnpinMessage(ctx context.Context, messageID uuid.UUID) (bool, error) {
	return chat.UnpinMessage(ctx, messageID)
}

// SendChannelMessage is the resolver for the sendChannelMessage field.
func (r *mutationResolver) SendChannelMessage(ctx context.Context, channelID uuid.UUID, body string, replyToID *uuid.UUID) (*model.Message, error) {
	return chat.SendChannelMessage(ctx, channelID, body, replyToID)
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, userID uuid.UUID, serverID uuid.UUID, roleID uuid.UUID) (bool, error) {
	return chat.AssignRole(ctx, userID, serverID, roleID)
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, serverID uuid.UUID, name string, permissions []string) (*model.Role, error) {
	return chat.CreateRole(ctx, serverID, name, permissions)
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, roleID uuid.UUID) (bool, error) {
	return chat.DeleteRole(ctx, roleID)
}

// EditMessage is the resolver for the editMessage field.
func (r *mutationResolver) EditMessage(ctx context.Context, messageID uuid.UUID, body string) (*model.Message, error) {
	return chat.EditMessage(ctx, messageID, body)
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, messageID uuid.UUID) (bool, error) {
	return chat.DeleteMessage(ctx, messageID)
}

// GetConversations is the resolver for the getConversations field.
func (r *queryResolver) GetConversations(ctx context.Context) ([]*model.Conversation, error) {
	return chat.GetConversations(ctx)
}

// GetMessages is the resolver for the getMessages field.
func (r *queryResolver) GetMessages(ctx context.Context, conversationID uuid.UUID) ([]*model.Message, error) {
	return chat.GetMessages(ctx, conversationID)
}

// GetServers is the resolver for the getServers field.
func (r *queryResolver) GetServers(ctx context.Context) ([]*model.Server, error) {
	return chat.GetServers(ctx)
}

// GetServer is the resolver for the getServer field.
func (r *queryResolver) GetServer(ctx context.Context, id uuid.UUID) (*model.Server, error) {
	return chat.GetServer(ctx, id)
}

// GetChannels is the resolver for the getChannels field.
func (r *queryResolver) GetChannels(ctx context.Context, serverID uuid.UUID) ([]*model.Channel, error) {
	return chat.GetChannels(ctx, serverID)
}

// GetChannelMessages is the resolver for the getChannelMessages field.
func (r *queryResolver) GetChannelMessages(ctx context.Context, channelID uuid.UUID) ([]*model.Message, error) {
	return chat.GetChannelMessages(ctx, channelID)
}

// GetDirectConversations is the resolver for the getDirectConversations field.
func (r *queryResolver) GetDirectConversations(ctx context.Context, limit *int32, after *time.Time) ([]*model.DirectConversation, error) {
	limitValue := 0
	if limit != nil {
		limitValue = int(*limit)
	}
	return chat.GetDirectConversations(ctx, limitValue, after)
}


// GetGroupConversations is the resolver for the getGroupConversations field.
func (r *queryResolver) GetGroupConversations(ctx context.Context, userID uuid.UUID, limit *int32, after *time.Time) ([]*model.GroupConversation, error) {
	panic(fmt.Errorf("not implemented: GetGroupConversations - getGroupConversations"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
