package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/Evantopian/Nexus/graph/model"
	"github.com/google/uuid"
)

// CreateLFGPost is the resolver for the createLFGPost field.
func (r *mutationResolver) CreateLFGPost(ctx context.Context, gameID uuid.UUID, serverID *uuid.UUID, title string, description string, requirements []string, tags []string, expiresAt *string) (*model.LFGPost, error) {
	panic(fmt.Errorf("not implemented: CreateLFGPost - createLFGPost"))
}

// DeleteLFGPost is the resolver for the deleteLFGPost field.
func (r *mutationResolver) DeleteLFGPost(ctx context.Context, postID uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteLFGPost - deleteLFGPost"))
}

// GetLFGPosts is the resolver for the getLFGPosts field.
func (r *queryResolver) GetLFGPosts(ctx context.Context, slug string) ([]*model.LFGPost, error) {
	panic(fmt.Errorf("not implemented: GetLFGPosts - getLFGPosts"))
}
