package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/Evantopian/Nexus/graph/model"
	"github.com/Evantopian/Nexus/graph/resolver"
	"github.com/google/uuid"
)

// RefreshRecommendations is the resolver for the refreshRecommendations field.
func (r *mutationResolver) RefreshRecommendations(ctx context.Context) (bool, error) {
	return resolver.RefreshRecommendations(ctx)
}

// GetRecommendations is the resolver for the getRecommendations field.
func (r *queryResolver) GetRecommendations(ctx context.Context, id uuid.UUID, limit *int32) ([]*model.Recommendation, error) {
	return resolver.GetRecommendations(ctx, id, limit)
}