package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/Evantopian/Nexus/graph/model"
	"github.com/Evantopian/Nexus/graph/resolver"
	"github.com/google/uuid"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, username *string, email *string, password *string, profileImg *string, profileMessage *string, status *string, rank *string) (*model.User, error) {
	return resolver.UpdateUser(ctx, username, email, password, profileImg, profileMessage, status, rank)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context) (bool, error) {
	return resolver.DeleteUser(ctx)
}

// AdjustRep is the resolver for the adjustRep field.
func (r *mutationResolver) AdjustRep(ctx context.Context, amount int32) (bool, error) {
	return resolver.AdjustRep(ctx, int(amount))
}

// UpdatePreference is the resolver for the updatePreference field.
func (r *mutationResolver) UpdatePreference(ctx context.Context, region *string, playstyle *model.Playstyle) (*model.Preferences, error) {
	return resolver.UpdatePreference(ctx, region, playstyle)
}

// SendFriendRequest is the resolver for the sendFriendRequest field.
func (r *mutationResolver) SendFriendRequest(ctx context.Context, receiverID uuid.UUID) (*model.FriendRequest, error) {
	return resolver.SendFriendRequest(ctx, receiverID)
}

// AcceptFriendRequest is the resolver for the acceptFriendRequest field.
func (r *mutationResolver) AcceptFriendRequest(ctx context.Context, senderID uuid.UUID) (bool, error) {
	return resolver.AcceptFriendRequest(ctx, senderID)
}

// RejectFriendRequest is the resolver for the rejectFriendRequest field.
func (r *mutationResolver) RejectFriendRequest(ctx context.Context, senderID uuid.UUID) (bool, error) {
	return resolver.RejectFriendRequest(ctx, senderID)
}

// RemoveFriend is the resolver for the removeFriend field.
func (r *mutationResolver) RemoveFriend(ctx context.Context, friendID uuid.UUID) (bool, error) {
	return resolver.RemoveFriend(ctx, friendID)
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*model.User, error) {
	return resolver.Profile(ctx)
}

// GetFriends is the resolver for the getFriends field.
func (r *queryResolver) GetFriends(ctx context.Context) ([]*model.User, error) {
	return resolver.GetFriends(ctx)
}

// GetFriendRequests is the resolver for the getFriendRequests field.
func (r *queryResolver) GetFriendRequests(ctx context.Context) (*model.FriendRequestsList, error) {
	return resolver.GetFriendRequests(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
