package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/Evantopian/Nexus/graph/model"
	"github.com/google/uuid"
)

// CreateServer is the resolver for the createServer field.
func (r *mutationResolver) CreateServer(ctx context.Context, gameID *uuid.UUID, name string, image *string, description *string) (*model.Server, error) {
	panic(fmt.Errorf("not implemented: CreateServer - createServer"))
}

// JoinServer is the resolver for the joinServer field.
func (r *mutationResolver) JoinServer(ctx context.Context, serverID uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: JoinServer - joinServer"))
}

// LeaveServer is the resolver for the leaveServer field.
func (r *mutationResolver) LeaveServer(ctx context.Context, serverID uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: LeaveServer - leaveServer"))
}

// DeleteServer is the resolver for the deleteServer field.
func (r *mutationResolver) DeleteServer(ctx context.Context, serverID uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteServer - deleteServer"))
}

// GetServers is the resolver for the getServers field.
func (r *queryResolver) GetServers(ctx context.Context, slug string) ([]*model.Server, error) {
	panic(fmt.Errorf("not implemented: GetServers - getServers"))
}
